### ISSUE TITLE
custom gui element implementation

### ISSUE THREAD

**Issue by adriente** [hyperspy/hyperspy#3478]
### Aim

I would like to implement my own version of "set_microscope_parameters" gui.

### Current try

The code below is strongly inspired from exspy but it can't work since exspy calls a function implemented in hyperspy-gui-traitsui (or ipywidgets). 

signal.py file
``````python
from hyperspy._signals.signal1d import Signal1D
from hyperspy.signal import BaseSetMetadataItems
import traits.api as t
from hyperspy.ui_registry import add_gui_method

@add_gui_method(toolkey="hspy_ext.my_parameters_MySignal")
class MySignalParametersUI(BaseSetMetadataItems):
    beam_energy = t.Float(t.Undefined, label="Beam energy (keV)")
    real_time = t.Float(t.Undefined, label="Real time (s)")
    mapping = {
        "beam_energy": "beam_energy",
        "real_time": "real_time",
    }

class MySignal(Signal1D):
    _signal_type = "MySignal"
    _signal_dimension = 1

    def create_model(self, dictionary=None):
        from hspy_ext.model import MyModel
        return MyModel(self, dictionary=dictionary)
    
    def set_my_parameters(self, beam_energy=None, real_time=None, display=True, toolkit=None):
        if set(
            [
                beam_energy,
                real_time
            ]
        ) == {None}:
            tem_par = MySignalParametersUI(self)
            return tem_par.gui(display=display, toolkit=toolkit)
        
        md = self.metadata
        if beam_energy is not None:
            md.set_item("beam_energy", beam_energy)
        if real_time is not None:
            md.set_item("real_time", real_time)
``````

and hyperspy.extension.yaml
``````yaml
signals:
  MySignal:
    signal_type: "MySignal"
    signal_dimension: 1
    dtype: real
    lazy: False
    module: hspy_ext.signal

components1D:.
  dcbd09ee-a420-4700-b60d-3a59e07e1237:
    module: hspy_ext.component
    class: MyComponent1D

GUI:
  toolkeys:
    - hspy_ext.MyComponent
    - hspy_ext.my_parameters_MySignal

  widgets:
    ipywidgets:
      hspy_ext.MyComponent:
        function: get_mycomponent_widget
        module: hspy_ext.widgets

      hspy_ext.my_parameters_MySignal :
        module: hspy_ext.signal
        function: ....
``````

I am stuck on how to define the function, since "set_my_parameters" is part of a class. Should I define the function externally and then call it from the class ? Even if I do that, it is also unclear for me how the appearance of the gui window is defined : shape, size, content, etc ... ?
From the other extensions of hyperspy I didn't find something like that.
